name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: $ {{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: $ {{ secrets.AWS_SECRET_ACCESS_KEY }}
      BUCKET_NAME: $ {{ secrets.BUCKET_NAME }}
      DEEPSEEK_API_KEY: $ {{ secrets.DEEPSEEK_API_KEY }}
      MY_EMAIL: $ {{ secrets.MY_EMAIL }}
      BOT_EMAIL: $ {{ secrets.BOT_EMAIL }}
      BOT_EMAIL_PASSWORD: $ {{ secrets.BOT_EMAIL_PASSWORD }}
    

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

          pip install -r requirements.txt

      - name: Lint and check syntax
        run: |
          python -m py_compile main.py

      - name: Run main script
        run: |
          python main.py
